name: CI and Deploy
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js and HTML5 Validator
      run: |
        sudo apt-get update
        sudo apt-get install -y npm
        npm install -g html5-validator
    - name: HTML5 Validation
      run: |
        html5-validator index.html
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to Surge
      run: |
        surge --project ./_build --domain tu-nombre.surge.sh
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

